<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>7804c3e6-2e58-4dff-96e9-4a2487a277c0</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>.</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Infrastructure\Persistence\**" />
	  <Compile Remove="Infrastructure\Resource\**" />
	  <Content Remove="Infrastructure\Persistence\**" />
	  <Content Remove="Infrastructure\Resource\**" />
	  <EmbeddedResource Remove="Infrastructure\Persistence\**" />
	  <EmbeddedResource Remove="Infrastructure\Resource\**" />
	  <None Remove="Infrastructure\Persistence\**" />
	  <None Remove="Infrastructure\Resource\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>



	<ItemGroup>
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.22" />
		<PackageReference Include="Hangfire.Core" Version="1.8.22" />
		<PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.1" />
		<PackageReference Include="Hangfire.MySql.Core_MySql.Data" Version="2.1.10" />
		<PackageReference Include="Hangfire.MySqlStorage" Version="2.0.3" />
		<PackageReference Include="MySql.Data" Version="9.5.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<!-- Prometheus metrics (prometheus-net) -->
		<PackageReference Include="prometheus-net.AspNetCore" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Application\ClientBilling\DTOs\" />
		<Folder Include="Application\ClientBilling\Services\" />
		<Folder Include="Application\PendingInvoicesBilling\DTOs\" />
		<Folder Include="Application\PendingInvoicesBilling\Services\" />
	</ItemGroup>

</Project>
